apply plugin: 'com.android.application'

android {
    compileSdk 35
    namespace "com.contextgenesis.perplexy"

    defaultConfig {
        applicationId "com.contextgenesis.perplexy"
        minSdk 21
        targetSdk 35
        versionCode 8
        versionName "1.5.pY.8"
    }
    buildFeatures {
        viewBinding true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    //implementation 'com.facebook.android:facebook-android-sdk:4.1.0'
    //above this version requires support library v23.2.0
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.fragment:fragment:1.8.5'
    implementation 'androidx.viewpager:viewpager:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'me.relex:circleindicator:2.1.6'
    implementation 'androidx.room:room-runtime:2.6.1'
    annotationProcessor 'androidx.room:room-compiler:2.6.1'
    implementation 'com.google.android.gms:play-services-ads:23.5.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.google.firebase:firebase-analytics:22.1.2'
    implementation 'com.unity3d.ads:unity-ads:4.12.5'
    implementation 'com.mikhaellopez:circularprogressbar:3.1.0'
    implementation 'com.android.billingclient:billing:7.0.0'
}

apply plugin: 'com.google.gms.google-services'
